name: Auto Deploy Laravel Project

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      # Step 1: Check out the latest code
      - name: Get the latest code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for asset building
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, json, fileinfo, openssl
          tools: composer

      # Step 4: Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step 5: Build front-end assets
      - name: Build Assets
        run: |
          npm install
          npm run build

      # Step 6: Sync files to server
      - name: Sync Files to Server
        uses: SamKirkLand/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./ # Deploy only updated files

      # Step 7: Clear cache on server
      - name: Clear Cache and Config
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Step 8: Fix directory permissions
      - name: Fix Directory Permissions
        run: chmod -R 775 storage bootstrap/cache